/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Amin;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author BERTIN FONGE
 */
public class Admin_panel extends javax.swing.JFrame {
         Color DefaultColor,ClickedColor;
    /**
     * Creates new form Admin_panel
     */
    public Admin_panel() {
        initComponents();
         initComponents();
        DefaultColor = new Color(0,153,153);
        ClickedColor = new Color(0,255,204);
         Toolkit toolkit = getToolkit();
         Dimension size = toolkit.getScreenSize();
         setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
         
        notific.setBackground(DefaultColor);
        a_admin.setBackground(DefaultColor);
        n_acc.setBackground(DefaultColor);
        a_mem.setBackground(DefaultColor);
        r_mem.setBackground(DefaultColor);
        a_with.setBackground(DefaultColor);
        r_usr.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        JPanell = new javax.swing.JPanel();
        menuname = new javax.swing.JLabel();
        notific = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        a_admin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        a_mem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        n_acc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        r_mem = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        a_with = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        r_usr = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 732, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        JPanell.setBackground(new java.awt.Color(0, 153, 153));

        menuname.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        menuname.setText("MENU");

        javax.swing.GroupLayout JPanellLayout = new javax.swing.GroupLayout(JPanell);
        JPanell.setLayout(JPanellLayout);
        JPanellLayout.setHorizontalGroup(
            JPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanellLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuname, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        JPanellLayout.setVerticalGroup(
            JPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanellLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(menuname)
                .addContainerGap())
        );

        notific.setBackground(new java.awt.Color(0, 153, 153));
        notific.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notificMousePressed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        label2.setText("NOTIFICATIONS");

        javax.swing.GroupLayout notificLayout = new javax.swing.GroupLayout(notific);
        notific.setLayout(notificLayout);
        notificLayout.setHorizontalGroup(
            notificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(label2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        notificLayout.setVerticalGroup(
            notificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, notificLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(label2)
                .addContainerGap())
        );

        a_admin.setBackground(new java.awt.Color(0, 153, 153));
        a_admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_adminMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a_adminMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel1.setText(" ADD ADMIN");

        javax.swing.GroupLayout a_adminLayout = new javax.swing.GroupLayout(a_admin);
        a_admin.setLayout(a_adminLayout);
        a_adminLayout.setHorizontalGroup(
            a_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_adminLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        a_adminLayout.setVerticalGroup(
            a_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        a_mem.setBackground(new java.awt.Color(0, 153, 153));
        a_mem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_memMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a_memMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel4.setText("APP MEMBER");

        javax.swing.GroupLayout a_memLayout = new javax.swing.GroupLayout(a_mem);
        a_mem.setLayout(a_memLayout);
        a_memLayout.setHorizontalGroup(
            a_memLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_memLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        a_memLayout.setVerticalGroup(
            a_memLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_memLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        n_acc.setBackground(new java.awt.Color(0, 153, 153));
        n_acc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                n_accMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                n_accMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setText("NJANGI ACCOUNT");

        javax.swing.GroupLayout n_accLayout = new javax.swing.GroupLayout(n_acc);
        n_acc.setLayout(n_accLayout);
        n_accLayout.setHorizontalGroup(
            n_accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, n_accLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(64, 64, 64))
        );
        n_accLayout.setVerticalGroup(
            n_accLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(n_accLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        r_mem.setBackground(new java.awt.Color(0, 153, 153));
        r_mem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_memMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                r_memMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Transfer funds");

        javax.swing.GroupLayout r_memLayout = new javax.swing.GroupLayout(r_mem);
        r_mem.setLayout(r_memLayout);
        r_memLayout.setHorizontalGroup(
            r_memLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, r_memLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(64, 64, 64))
        );
        r_memLayout.setVerticalGroup(
            r_memLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(r_memLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        a_with.setBackground(new java.awt.Color(0, 153, 153));
        a_with.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                a_withMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel5.setText("APP WITHDRAWAL");

        javax.swing.GroupLayout a_withLayout = new javax.swing.GroupLayout(a_with);
        a_with.setLayout(a_withLayout);
        a_withLayout.setHorizontalGroup(
            a_withLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, a_withLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(43, 43, 43))
        );
        a_withLayout.setVerticalGroup(
            a_withLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(a_withLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        r_usr.setBackground(new java.awt.Color(0, 153, 153));
        r_usr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_usrMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                r_usrMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel7.setText("REMOVE USER");

        javax.swing.GroupLayout r_usrLayout = new javax.swing.GroupLayout(r_usr);
        r_usr.setLayout(r_usrLayout);
        r_usrLayout.setHorizontalGroup(
            r_usrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(r_usrLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        r_usrLayout.setVerticalGroup(
            r_usrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(r_usrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notific, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(a_admin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(a_mem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(n_acc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(r_mem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(r_usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(a_with, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(notific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(a_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(n_acc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(a_mem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(r_mem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(a_with, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(r_usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel2.setText("NJANGI 4 YOU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel2)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 749, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 515, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jDesktopPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificMouseClicked
        // TODO add your handling code here:
        Admin_Send notifications = new Admin_Send();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(notifications).setVisible(true);
    }//GEN-LAST:event_notificMouseClicked

    private void notificMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificMousePressed
        // TODO add your handling code here:
        notific.setBackground(ClickedColor);
        a_admin.setBackground(DefaultColor);
        n_acc.setBackground(DefaultColor);
        a_mem.setBackground(DefaultColor);
        r_mem.setBackground(DefaultColor);
        a_with.setBackground(DefaultColor);
        r_usr.setBackground(DefaultColor);
        menuname.setText("NOTIFICATIONS");
    }//GEN-LAST:event_notificMousePressed

    private void a_adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_adminMouseClicked
        // TODO add your handling code here:
        Add_A obj = new Add_A();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_a_adminMouseClicked

    private void a_adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_adminMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        a_admin.setBackground(ClickedColor);
        n_acc.setBackground(DefaultColor);
        a_mem.setBackground(DefaultColor);
        r_mem.setBackground(DefaultColor);
        a_with.setBackground(DefaultColor);
        r_usr.setBackground(DefaultColor);
        menuname.setText("ADD ADMIN");
    }//GEN-LAST:event_a_adminMousePressed

    private void a_memMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_memMouseClicked
        // TODO add your handling code here:
        Approve_M obj = new Approve_M();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_a_memMouseClicked

    private void a_memMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_memMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        a_admin.setBackground(DefaultColor);
        n_acc.setBackground(DefaultColor);
        a_mem.setBackground(ClickedColor);
        r_mem.setBackground(DefaultColor);
        a_with.setBackground(DefaultColor);
        r_usr.setBackground(DefaultColor);
        menuname.setText("APP MEMBER");
    }//GEN-LAST:event_a_memMousePressed

    private void n_accMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n_accMouseClicked
        // TODO add your handling code here:
        Njangi obj = new Njangi();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_n_accMouseClicked

    private void n_accMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_n_accMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        a_admin.setBackground(DefaultColor);
        n_acc.setBackground(ClickedColor);
        a_mem.setBackground(DefaultColor);
        r_mem.setBackground(DefaultColor);
        a_with.setBackground(DefaultColor);
        r_usr.setBackground(DefaultColor);
        menuname.setText("NJANGI ACCOUNT");
    }//GEN-LAST:event_n_accMousePressed

    private void r_memMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_memMouseClicked
        // TODO add your handling code here:
        Transfer obj = new Transfer();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_r_memMouseClicked

    private void r_memMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_memMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        a_admin.setBackground(DefaultColor);
        n_acc.setBackground(DefaultColor);
        a_mem.setBackground(DefaultColor);
        r_mem.setBackground(ClickedColor);
        a_with.setBackground(DefaultColor);
        r_usr.setBackground(DefaultColor);
        menuname.setText("REMOVE MEM");
    }//GEN-LAST:event_r_memMousePressed

    private void a_withMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_withMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        a_admin.setBackground(DefaultColor);
        n_acc.setBackground(DefaultColor);
        a_mem.setBackground(DefaultColor);
        r_mem.setBackground(DefaultColor);
        a_with.setBackground(ClickedColor);
        r_usr.setBackground(DefaultColor);
        menuname.setText("APP WITDRAWAL");
    }//GEN-LAST:event_a_withMousePressed

    private void r_usrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_usrMouseClicked
        // TODO add your handling code here:
        Delete_M obj = new Delete_M();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_r_usrMouseClicked

    private void r_usrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_usrMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        a_admin.setBackground(DefaultColor);
        n_acc.setBackground(DefaultColor);
        a_mem.setBackground(DefaultColor);
        r_mem.setBackground(DefaultColor);
        a_with.setBackground(DefaultColor);
        r_usr.setBackground(ClickedColor);
        menuname.setText("REMOVE USER");
    }//GEN-LAST:event_r_usrMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanell;
    private javax.swing.JPanel a_admin;
    private javax.swing.JPanel a_mem;
    private javax.swing.JPanel a_with;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel menuname;
    private javax.swing.JPanel n_acc;
    private javax.swing.JPanel notific;
    private javax.swing.JPanel r_mem;
    private javax.swing.JPanel r_usr;
    // End of variables declaration//GEN-END:variables
}
