/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Amin;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author BERTIN FONGE
 */
public class memeber extends javax.swing.JFrame {
     Color DefaultColor,ClickedColor;
    /**
     * Creates new form memeber
     */
    public memeber() {
        initComponents();
         DefaultColor = new Color(0,153,153);
        ClickedColor = new Color(0,255,204);
         Toolkit toolkit = getToolkit();
         Dimension size = toolkit.getScreenSize();
         setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        
        
        
        
        //set default color to pan on run time
        notific.setBackground(DefaultColor);
        sav.setBackground(DefaultColor);
        contri.setBackground(DefaultColor);
        njan.setBackground(DefaultColor);
        borr.setBackground(DefaultColor);
        depo.setBackground(DefaultColor);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        notific = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        sav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        contri = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        njan = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        borr = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        JPanell = new javax.swing.JPanel();
        menuname = new javax.swing.JLabel();
        depo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1050, 700));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        notific.setBackground(new java.awt.Color(0, 153, 153));
        notific.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notificMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notificMousePressed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        label2.setText("NOTIFICATIONS");

        javax.swing.GroupLayout notificLayout = new javax.swing.GroupLayout(notific);
        notific.setLayout(notificLayout);
        notificLayout.setHorizontalGroup(
            notificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        notificLayout.setVerticalGroup(
            notificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notificLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sav.setBackground(new java.awt.Color(0, 153, 153));
        sav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                savMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jLabel1.setText("SAVINGS");

        javax.swing.GroupLayout savLayout = new javax.swing.GroupLayout(sav);
        sav.setLayout(savLayout);
        savLayout.setHorizontalGroup(
            savLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        savLayout.setVerticalGroup(
            savLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        contri.setBackground(new java.awt.Color(0, 153, 153));
        contri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contriMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                contriMousePressed(evt);
            }
        });

        label4.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        label4.setText("CONTRIBUTIONS");

        javax.swing.GroupLayout contriLayout = new javax.swing.GroupLayout(contri);
        contri.setLayout(contriLayout);
        contriLayout.setHorizontalGroup(
            contriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contriLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(label4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contriLayout.setVerticalGroup(
            contriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        njan.setBackground(new java.awt.Color(0, 153, 153));
        njan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                njanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                njanMousePressed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        label5.setText("Withdraw");

        javax.swing.GroupLayout njanLayout = new javax.swing.GroupLayout(njan);
        njan.setLayout(njanLayout);
        njanLayout.setHorizontalGroup(
            njanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(njanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        njanLayout.setVerticalGroup(
            njanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(njanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        borr.setBackground(new java.awt.Color(0, 153, 153));
        borr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                borrMousePressed(evt);
            }
        });

        label6.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        label6.setText("BORROW");

        javax.swing.GroupLayout borrLayout = new javax.swing.GroupLayout(borr);
        borr.setLayout(borrLayout);
        borrLayout.setHorizontalGroup(
            borrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(label6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        borrLayout.setVerticalGroup(
            borrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        JPanell.setBackground(new java.awt.Color(0, 153, 153));

        menuname.setFont(new java.awt.Font("Showcard Gothic", 1, 12)); // NOI18N
        menuname.setText("MENU");

        javax.swing.GroupLayout JPanellLayout = new javax.swing.GroupLayout(JPanell);
        JPanell.setLayout(JPanellLayout);
        JPanellLayout.setHorizontalGroup(
            JPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanellLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        JPanellLayout.setVerticalGroup(
            JPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuname)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        depo.setBackground(new java.awt.Color(0, 153, 153));
        depo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                depoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                depoMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel3.setText("DEPOSIT");

        javax.swing.GroupLayout depoLayout = new javax.swing.GroupLayout(depo);
        depo.setLayout(depoLayout);
        depoLayout.setHorizontalGroup(
            depoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        depoLayout.setVerticalGroup(
            depoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(njan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(borr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notific, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(depo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(JPanell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(notific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(njan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(borr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(depo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jLabel2.setText("NJANGI 4 YOU");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addContainerGap(69, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(680, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 210, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificMouseClicked
        // TODO add your handling code here:
        notific notifications = new notific();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(notifications).setVisible(true);
    }//GEN-LAST:event_notificMouseClicked

    private void notificMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificMousePressed
        // TODO add your handling code here:
        notific.setBackground(ClickedColor);
        sav.setBackground(DefaultColor);
        contri.setBackground(DefaultColor);
        njan.setBackground(DefaultColor);
        borr.setBackground(DefaultColor);
        depo.setBackground(DefaultColor);
        menuname.setText("NOTIFICATIONS");
    }//GEN-LAST:event_notificMousePressed

    private void savMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savMouseClicked
        // TODO add your handling code here:
        Accounts obj = new Accounts();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_savMouseClicked

    private void savMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        sav.setBackground(ClickedColor);
        contri.setBackground(DefaultColor);
        njan.setBackground(DefaultColor);
        borr.setBackground(DefaultColor);
        depo.setBackground(DefaultColor);
        menuname.setText("SAVINGS");
    }//GEN-LAST:event_savMousePressed

    private void contriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contriMouseClicked
        // TODO add your handling code here:
        Contribution obj = new Contribution();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_contriMouseClicked

    private void contriMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contriMousePressed
        // TODO add your handling code here
        notific.setBackground(DefaultColor);
        sav.setBackground(DefaultColor);
        contri.setBackground(ClickedColor);
        njan.setBackground(DefaultColor);
        borr.setBackground(DefaultColor);
        depo.setBackground(DefaultColor);
        menuname.setText("CONTRIBUTIONS");
    }//GEN-LAST:event_contriMousePressed

    private void njanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_njanMouseClicked
        // TODO add your handling code here:
        Wiithdraw obj = new Wiithdraw();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_njanMouseClicked

    private void njanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_njanMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        sav.setBackground(DefaultColor);
        contri.setBackground(DefaultColor);
        njan.setBackground(ClickedColor);
        borr.setBackground(DefaultColor);
        depo.setBackground(DefaultColor);
        menuname.setText("NJANGI");
    }//GEN-LAST:event_njanMousePressed

    private void borrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrMouseClicked
        // TODO add your handling code here:
        Borrow obj = new Borrow();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_borrMouseClicked

    private void borrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        sav.setBackground(DefaultColor);
        contri.setBackground(DefaultColor);
        njan.setBackground(DefaultColor);
        borr.setBackground(ClickedColor);
        depo.setBackground(DefaultColor);
        menuname.setText("BORROW");
    }//GEN-LAST:event_borrMousePressed

    private void depoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depoMouseClicked
        // TODO add your handling code here:
        Deposit obj = new Deposit();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(obj).setVisible(true);
    }//GEN-LAST:event_depoMouseClicked

    private void depoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_depoMousePressed
        // TODO add your handling code here:
        notific.setBackground(DefaultColor);
        sav.setBackground(DefaultColor);
        contri.setBackground(DefaultColor);
        njan.setBackground(DefaultColor);
        borr.setBackground(DefaultColor);
        depo.setBackground(ClickedColor);
        menuname.setText("DEPOSIT");
    }//GEN-LAST:event_depoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memeber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memeber().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanell;
    private javax.swing.JPanel borr;
    private javax.swing.JPanel contri;
    private javax.swing.JPanel depo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel menuname;
    private javax.swing.JPanel njan;
    private javax.swing.JPanel notific;
    private javax.swing.JPanel sav;
    // End of variables declaration//GEN-END:variables
}
